apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: checkout-service
  namespace: observability
  labels:
    app.kubernetes.io/name: checkout-service
    app.kubernetes.io/part-of: observability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout-service
