apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-microservices
  namespace: observability
  labels:
    app.kubernetes.io/name: sample-microservices
    app.kubernetes.io/part-of: observability
automountServiceAccountToken: true
