apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch
  namespace: observability
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: observability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
